import AddAddressPage from './AddAddressPage'
import AddProductPage from './AddProductPage'
import AddressPage from './AddressPage'
import CartPage from './CartPage'
import HomePage from './HomePage'
import LoginPage from './LoginPage'
import ProductPage from './ProductPage'
import ProfileEditPage from './ProfileEditPage'
import ProfilePage from './ProfilePage'
import SignUpPage from './SignUpPage'
import SplashScreen from './SplashScreen'
import StorePage from './StorePage'
import WelcomePage from './WelcomePage'
import WishlistPage from './WishlistPage'

export { AddAddressPage, AddProductPage,AddressPage, CartPage, HomePage, LoginPage, ProductPage, ProfileEditPage, ProfilePage, SignUpPage, SplashScreen, StorePage, WelcomePage, WishlistPage};